---
- hosts: localhost
  tasks:
    - name: Create Environment.scala file
      template:
        src: ../project/Environment.scala.j2
        dest: ../project/Environment.scala
    - name: Create daf-catalog-manager.yml file
      template:
        src: ../kubernetes/daf-catalog-manager.yml.j2
        dest: ../kubernetes/daf-catalog-manager.yml
